version: "3.7"

services:
    client:
        restart: always
        environment:
            - ENV=production
        build:
            args:
                - ENV=production

    image_downloader:
        restart: always
        environment:
            - ENV=production
        build:
            args:
                - ENV=production

    listener:
        restart: always
        environment:
            - ENV=production
        build:
            args:
                - ENV=production

    web:
        restart: always
        environment:
            - ENV=production
        build:
            args:
                - ENV=production